# Site configuration
# 1. Files excluded from Jekyll builds
# 2. Installed Gems
# 3. Gem settings
# 4. Jekyll settings
# 5. Collections
# 6. Jekyll collections settings
# 7. Site settings
# 8. Site navigation

# 1. Files excluded from Jekyll builds
exclude:
- README.md
- LICENSE
- CNAME
- Gemfile
- Gemfile.lock
- vendor

# 2. Installed plugin gems
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jemoji
- github-pages
- jekyll-commonmark
- jekyll-include-cache

# 3. Gem settings
sass:
  style: compressed
  sass_dir: _sass

paginate: 8 # jekyll-paginate > items per page
paginate_path: "/blog/page:num/" # jekyll-paginate > blog page
jekyll-mentions: https://twitter.com # base url for jekyll mentions

compress_html:
  clippings: all

twitter:
  username: sergiogimenez6 # jekyll-seo-tag > Owners twitter username

author: Sergio Gimenez # jekyll-seo-tag > default author

# 4. Jekyll settings
sass:
  style: compressed # Style compression
permalink: /:categories/:title/  # define url construction
timezone: Europe/Madrid # Timezone for blog posts and alike

# 6. Site wide defaults
defaults:
  - scope:
      path: ""
      type: pages
    values:
      layout: page # Default layout
      #image: "/assets/img/kunal-logo.png" # Default image for sharing

  - scope:
      path: ""
      type: posts
    values:
      layout: post

  - scope:
      path: ""
      type: tag
    values:
      layout: tag
      
collections:
  tag:
      output: true

# 7. Site settings
encoding: utf-8 # Make sure the encoding is right
title: "Sergio Giménez" # Site name or title, also used in jekyll-seo-tag
#logo: "/assets/img/kunal-logo.png" # Site logo, also used in jekyll-seo-tag

# Site description and default description, also used in jekyll-seo-tag
url: "https://sergiogimenez.net" # Site url, also used in jekyll-seo-tag
repo: "https://github.com/sergio-gimenez/sergio-gimenez.github.io"
avatarurl: "https://avatars.githubusercontent.com/u/42917235?s=460&u=2c8b849e1072e9d5dc35e0a28f9c4d1fd19985a0&v=4"

# site verification
# webmaster_verifications:
#   google: sCRGg28ReGiDdQ4JQ75b6RCTtmBD9J6QQwh1kpIMDAU

# default markdown processor and highlighter
markdown: kramdown
highlighter: rouge
error_mode: strict

# 8. Site navigation
navigation_header:
  Home: /
  About: /about/
  Blog: /blog/

#site credits
navigation_footer:
  Alembic Theme: https://alembic.darn.es/
  Theme Inspired by @KunalBaweja: https://bawejakunal.github.io/

contact:
  github:     https://github.com/sergio-gimenez
  linkedin:   https://www.linkedin.com/in/sergio-gimant/
  twitter:    https://twitter.com/sergiogimenez6
  RSS:        /feed.xml
  # flickr:     https://www.flickr.com/photos/bawejakunal/
